services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    restart: unless-stopped
    command:
      - "--log.level=TRACE"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.defaultRule=Host(`notary.pse.dev`) && PathPrefix(`/{{ normalize (index .Labels \"com.docker.compose.service\") }}`)"
      - "--entrypoints.web.address=:80"
      - "--api.insecure=true"
      - "--api.dashboard=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  websockify:
    container_name: websockify-proxy
    image: jwnmulder/websockify:0.12
    restart: unless-stopped
    volumes:
      - "./websockify/websockify_config:/app/websockify_config"
    ports:
      - "55688:80"
    command: [ "80", "--target-config", "/app/websockify_config" ]
  nightly:
    container_name: nightly
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.stripnightly.stripprefix.prefixes=/nightly"
      - "traefik.http.routers.nightly.middlewares=stripnightly" 
    image: ghcr.io/tlsnotary/tlsn/notary-server-sgx:dev
    restart: unless-stopped
    devices:
      - /dev/sgx_enclave
      - /dev/sgx_provision
    volumes:
      - /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket
      - ./nightly/config.yaml:/work/config/config.yaml:ro
    ports:
      - "3333:7047"
    entrypoint: [ "gramine-sgx", "notary-server" ]
  alpha9:
    container_name: alpha9
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alpha9.rule=PathPrefix(`/v0.1.0-alpha.9`)"
      - "traefik.http.routers.alpha9.middlewares=stripalpha9" 
      - "traefik.http.middlewares.stripalpha9.stripprefix.prefixes=/v0.1.0-alpha.9"
    image: ghcr.io/tlsnotary/tlsn/notary-server-sgx:v0.1.0-alpha.9
    restart: unless-stopped
    devices:
      - /dev/sgx_enclave
      - /dev/sgx_provision
    volumes:
      - /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket
      - "./alpha9/fixture:/root/.notary-server/fixture"
      - "./alpha9/config:/root/.notary-server/config"
    ports:
      - "4009:7047"
    entrypoint: [ "gramine-sgx", "notary-server" ]
  alpha8:
    container_name: alpha8
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alpha8.rule=PathPrefix(`/v0.1.0-alpha.8`)"
      - "traefik.http.routers.alpha8.middlewares=stripalpha8" 
      - "traefik.http.middlewares.stripalpha8.stripprefix.prefixes=/v0.1.0-alpha.8"
    image: ghcr.io/tlsnotary/tlsn/notary-server-sgx:v0.1.0-alpha.8
    restart: unless-stopped
    devices:
      - /dev/sgx_enclave
      - /dev/sgx_provision
    volumes:
      - /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket
    ports:
      - "4008:7047"
    entrypoint: [ "gramine-sgx", "notary-server" ]
  alpha7:
    container_name: alpha7
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alpha7.rule=PathPrefix(`/v0.1.0-alpha.7`)"
      - "traefik.http.routers.alpha7.middlewares=stripalpha7" 
      - "traefik.http.middlewares.stripalpha7.stripprefix.prefixes=/v0.1.0-alpha.7"
    image: ghcr.io/tlsnotary/tlsn/notary-server:v0.1.0-alpha.7
    restart: unless-stopped
    volumes:
      - "./alpha7/fixture:/root/.notary-server/fixture"
      - "./alpha7/config:/root/.notary-server/config"
    ports:
      - "4007:7047"
  alpha6:
    container_name: alpha6
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alpha6.rule=PathPrefix(`/v0.1.0-alpha.6`)"
      - "traefik.http.routers.alpha6.middlewares=stripalpha6" 
      - "traefik.http.middlewares.stripalpha6.stripprefix.prefixes=/v0.1.0-alpha.6"
    image: ghcr.io/tlsnotary/tlsn/notary-server:v0.1.0-alpha.6
    restart: unless-stopped
    volumes:
      - "./alpha6/fixture:/root/.notary-server/fixture"
      - "./alpha6/config:/root/.notary-server/config"
    ports:
      - "4001:7047"
  alpha11-sgx:
    container_name: alpha11-sgx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alpha11-sgx.rule=PathPrefix(`/v0.1.0-alpha.11-sgx`)"
      - "traefik.http.routers.alpha11-sgx.middlewares=stripalpha11-sgx"
      - "traefik.http.middlewares.stripalpha11-sgx.stripprefix.prefixes=/v0.1.0-alpha.11-sgx"
    image: ghcr.io/tlsnotary/tlsn/notary-server-sgx:v0.1.0-alpha.11
    restart: unless-stopped
    devices:
      - /dev/sgx_enclave
      - /dev/sgx_provision
    volumes:
      - /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket
    ports:
      - "4110:7047"
    environment:
      - NS_CONCURRENCY:2
  alpha11:
    container_name: alpha11
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alpha11.rule=PathPrefix(`/v0.1.0-alpha.11`)"
      - "traefik.http.routers.alpha11.middlewares=stripalpha11"
      - "traefik.http.middlewares.stripalpha11.stripprefix.prefixes=/v0.1.0-alpha.11"
    image: ghcr.io/tlsnotary/tlsn/notary-server:v0.1.0-alpha.11
    restart: unless-stopped
    ports:
      - "4010:7047"
    environment:
      - NS_CONCURRENCY:10
  alpha10-sgx:
    container_name: alpha10-sgx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alpha10-sgx.rule=PathPrefix(`/v0.1.0-alpha.10-sgx`)"
      - "traefik.http.routers.alpha10-sgx.middlewares=stripalpha10-sgx" 
      - "traefik.http.middlewares.stripalpha10-sgx.stripprefix.prefixes=/v0.1.0-alpha.10-sgx"
    image: ghcr.io/tlsnotary/tlsn/notary-server-sgx:v0.1.0-alpha.10
    restart: unless-stopped
    devices:
      - /dev/sgx_enclave
      - /dev/sgx_provision
    volumes:
      - /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket
      # workaround for https://github.com/tlsnotary/tlsn/pull/791
      - ./alpha10-sgx/config.yaml:/work/config/config.yaml:ro
    ports:
      - "4110:7047"
    entrypoint: [ "gramine-sgx", "notary-server" ]
  alpha10:
    container_name: alpha10
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alpha10.rule=PathPrefix(`/v0.1.0-alpha.10`)"
      - "traefik.http.routers.alpha10.middlewares=stripalpha10" 
      - "traefik.http.middlewares.stripalpha10.stripprefix.prefixes=/v0.1.0-alpha.10"
    image: ghcr.io/tlsnotary/tlsn/notary-server:v0.1.0-alpha.10
    restart: unless-stopped
    volumes:
      - "./alpha10/fixture:/root/.notary-server/fixture"
      - "./alpha10/config:/root/.notary-server/config"
    ports:
      - "4010:7047"
  alpha9-sgx:
    container_name: alpha9-sgx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alpha9-sgx.rule=PathPrefix(`/v0.1.0-alpha.9-sgx`)"
      - "traefik.http.routers.alpha9-sgx.middlewares=stripalpha9-sgx" 
      - "traefik.http.middlewares.stripalpha9-sgx.stripprefix.prefixes=/v0.1.0-alpha.9-sgx"
    image: ghcr.io/tlsnotary/tlsn/notary-server-sgx:v0.1.0-alpha.9
    restart: unless-stopped
    devices:
      - /dev/sgx_enclave
      - /dev/sgx_provision
    volumes:
      - /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket
    ports:
      - "4109:7047"
    entrypoint: [ "gramine-sgx", "notary-server" ]
