services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    restart: unless-stopped
    command:
      - "--log.level=TRACE"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.defaultRule=Host(`notary.pse.dev`) && PathPrefix(`/{{ normalize (index .Labels \"com.docker.compose.service\") }}`)"
      - "--entrypoints.web.address=:80"
      - "--api.insecure=true"
      - "--api.dashboard=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  websockify:
    container_name: websockify-proxy
    image: jwnmulder/websockify:0.12
    restart: unless-stopped
    volumes:
      - "./websockify/websockify_config:/app/websockify_config"
    ports:
      - "55688:80"
    command: [ "80", "--target-config", "/app/websockify_config" ]
  nightly:
    container_name: nightly
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.stripnightly.stripprefix.prefixes=/nightly"
      - "traefik.http.routers.nightly.middlewares=stripnightly" 
    image: ghcr.io/tlsnotary/tlsn/notary-server-sgx:dev
    restart: unless-stopped
    devices:
      - /dev/sgx_enclave
      - /dev/sgx_provision
    volumes:
      - /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket
      - ./nightly/config.yaml:/work/config/config.yaml:ro
    ports:
      - "3333:7047"
    entrypoint: [ "gramine-sgx", "notary-server" ]
  alpha12-sgx:
    container_name: alpha12-sgx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alpha12-sgx.rule=PathPrefix(`/v0.1.0-alpha.12-sgx`)"
      - "traefik.http.routers.alpha12-sgx.middlewares=stripalpha12-sgx"
      - "traefik.http.middlewares.stripalpha12-sgx.stripprefix.prefixes=/v0.1.0-alpha.12-sgx"
    image: ghcr.io/tlsnotary/tlsn/notary-server-sgx:v0.1.0-alpha.12
    restart: unless-stopped
    devices:
      - /dev/sgx_enclave
      - /dev/sgx_provision
    volumes:
      - /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket
    ports:
      - "4112:7047"
    environment:
      - NS_CONCURRENCY:2
  alpha12:
    container_name: alpha12
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alpha12.rule=PathPrefix(`/v0.1.0-alpha.12`)"
      - "traefik.http.routers.alpha12.middlewares=stripalpha12"
      - "traefik.http.middlewares.stripalpha12.stripprefix.prefixes=/v0.1.0-alpha.12"
    image: ghcr.io/tlsnotary/tlsn/notary-server:v0.1.0-alpha.12
    restart: unless-stopped
    ports:
      - "4012:7047"
    environment:
      - NS_CONCURRENCY:10
  alpha11-sgx:
    container_name: alpha11-sgx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alpha11-sgx.rule=PathPrefix(`/v0.1.0-alpha.11-sgx`)"
      - "traefik.http.routers.alpha11-sgx.middlewares=stripalpha11-sgx"
      - "traefik.http.middlewares.stripalpha11-sgx.stripprefix.prefixes=/v0.1.0-alpha.11-sgx"
    image: ghcr.io/tlsnotary/tlsn/notary-server-sgx:v0.1.0-alpha.11
    restart: unless-stopped
    devices:
      - /dev/sgx_enclave
      - /dev/sgx_provision
    volumes:
      - /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket
    ports:
      - "4111:7047"
    environment:
      - NS_CONCURRENCY:2
  alpha11:
    container_name: alpha11
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alpha11.rule=PathPrefix(`/v0.1.0-alpha.11`)"
      - "traefik.http.routers.alpha11.middlewares=stripalpha11"
      - "traefik.http.middlewares.stripalpha11.stripprefix.prefixes=/v0.1.0-alpha.11"
    image: ghcr.io/tlsnotary/tlsn/notary-server:v0.1.0-alpha.11
    restart: unless-stopped
    ports:
      - "4011:7047"
    environment:
      - NS_CONCURRENCY:10
  alpha10-sgx:
    container_name: alpha10-sgx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alpha10-sgx.rule=PathPrefix(`/v0.1.0-alpha.10-sgx`)"
      - "traefik.http.routers.alpha10-sgx.middlewares=stripalpha10-sgx" 
      - "traefik.http.middlewares.stripalpha10-sgx.stripprefix.prefixes=/v0.1.0-alpha.10-sgx"
    image: ghcr.io/tlsnotary/tlsn/notary-server-sgx:v0.1.0-alpha.10
    restart: unless-stopped
    devices:
      - /dev/sgx_enclave
      - /dev/sgx_provision
    volumes:
      - /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket
      # workaround for https://github.com/tlsnotary/tlsn/pull/791
      - ./alpha10-sgx/config.yaml:/work/config/config.yaml:ro
    ports:
      - "4110:7047"
    entrypoint: [ "gramine-sgx", "notary-server" ]
  alpha10:
    container_name: alpha10
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alpha10.rule=PathPrefix(`/v0.1.0-alpha.10`)"
      - "traefik.http.routers.alpha10.middlewares=stripalpha10" 
      - "traefik.http.middlewares.stripalpha10.stripprefix.prefixes=/v0.1.0-alpha.10"
    image: ghcr.io/tlsnotary/tlsn/notary-server:v0.1.0-alpha.10
    restart: unless-stopped
    volumes:
      - "./alpha10/fixture:/root/.notary-server/fixture"
      - "./alpha10/config:/root/.notary-server/config"
    ports:
      - "4010:7047"